# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=600)),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
                ('tags', models.CharField(max_length=300)),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
        ),
    ]
