# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(max_length=30),
        ),
    ]
