# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('title', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=600)),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
                ('tags', models.CharField(max_length=30)),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
