# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-02 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200302_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumb',
        ),
    ]
