# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-03 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_image_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='createad',
            new_name='created',
        ),
    ]
